DROP TABLE USERS;
CREATE TABLE USERS (
	ID INT NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(100) DEFAULT NULL,
	LASTNAME  VARCHAR(100) DEFAULT NULL,
	EMAIL  	  VARCHAR(256) DEFAULT NULL,
	PHONE 	  VARCHAR(22) DEFAULT NULL,
	STATUS 	  VARCHAR(25) DEFAULT NULL,
	ADDRESS   VARCHAR(100) DEFAULT NULL,
	DATE_OF_BIRTH DATE DEFAULT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT UNIQUE_COLS UNIQUE(EMAIL,PHONE)
);